### PR TITLE
PYT-1971 Removed python2 dependent code and coverage back to 100%

### PR DESCRIPTION
**Pull request by angelobretenovv**
**For Contrast Python Developers Only**:

- [x] I've created a PR to update the vulnpy commit

- [ ] We do not want to update to this PR's top commit.

Returning back the coverage to 100% and removing py2 dependent code, seems like we don't need six anymore here, do we?

### CODE REVIEW

**Comment by angelobretenovv** [comment]
Let me know if I should remove the whole externed six here as well.

**Review by lazorchakp — CHANGES_REQUESTED** [review]
if you could also remove `six` too, that would be great.

There are probably still a few places where we can trim out some old code, but at least with coverage back to 100% we know that nothing fails (it just may be redundant)

**Comment by danilito19** [comment]
once Peter's suggestions are good, copy the latest commit in this PR and update the python agent VULNPY_COMMIT and create a PR there too (that's what the PR description hints at)

**Review by lazorchakp — APPROVED** [review]
looks great. Thanks for the string utils + tests as well

**Pull request merged**
