### PR TITLE
PYT-1003 Add SSRF

### PR DESCRIPTION
**Pull request by lazorchakp**
- Adds SSRF
- There are a lot of triggers for SSRF
- I kept in some "safe" triggers because we currently have apptest for these cases too

- Previously, we had mocked out a critical function that actually causes a real network request to be sent. Is it irresponsible not to do this? We end up firing around a dozen requests to example.com whenever we run the unit tests locally (x5 for the pipelines). I feel like this is alright, and in the spirit of the project I'd prefer if this vulnerability was "real" in the sample webapps. Lmk what you think about this

### CODE REVIEW

**Comment by danilito19** [comment]
> * Is it irresponsible not to do this?

No - but it is a design choice that should be heavily documented to avoid upset clients! This is what I suggest:  for every SSRF trigger that makes a real request to example.com, add an attr like `live=True` and document that `live=True` means a live request. Make the default `False`, because I believe in most cases users would not want live. What do you think?

**Comment by lazorchakp** [comment]
@danilito19 I like it a lot. I'll rework this a bit to make it happen

**Comment by lazorchakp** [comment]
I'm still considering moving these mocks to the actual `ssrf.py` module with an env var for disabling them (which will only be used for the apps provided by `make`). I'll re-request reviews when I'm done with that - and the work will be in separate commits so we can decide which makes more sense

**Comment by lazorchakp** [comment]
Reviewers: the two newest commits on this branch add SSRF mocking. The first only performs this mocking in unit testing, and the second mocks by default everywhere. I personally like the current implementation (mocking by default in the source code) since this means connections will also be mocked in our apptests.

**Review by danilito19 — APPROVED** [review]
Love the decorator pattern use!

**Pull request merged**
